### ISSUE TITLE
Dynamic configurations to update mqsc without restarting the POD

### ISSUE THREAD

**Issue by uaw013** [ibm-messaging/mq-helm#82]
Hi,

We are able to create queues, channels topics etc, but everytime we need 
to restart the pod before the change is activated. 
below the base-helm-values what we used, this works. 
queueManager:
  mqscConfigMaps:
    - name: mq-tst-config-qm
      items:
        - queues.mqsc
 
We would like to add or remove queues with zero downtime. What is the best practices to do that?

Platform Kubernetes. 
Client Version: v1.26.9
Kustomize Version: v4.5.7
Server Version: v1.27.11

**Comment by gevezex** [comment]
I am also very interested for the solution 👍🏻

**Comment by arthurbarr** [comment]
MQ has the _option_ of using declarative configuration, but all the other options are still available.  MQ's declarative "auto config" feature (used by the container) was written to apply MQSC and INI files at queue manager start up time.  This was mainly so that if it goes wrong, then MQ can roll back to the previous working configuration.

If you are confident that your configuration changes will work against a running queue manager, with connected and active applications, then you can still use any of the other configuration options MQ offers, including running MQSC scripts with `runmqsc`, using the REST admin API, using the MQ message-based (PCF) administration, using the MQ web console, the old MQ Explorer UI, or any number of tools which build on top of these.

For example, one approach might be that when you change an MQSC file in source control, your CI/CD pipeline also does a `kubectl exec` to run `runmqsc` to apply it immediately.  This way, you still have a "declarative" configuration, but it is applied immediately.  You need to do your own pre-validation of that change though, because if you're applying it to a live production queue manager, you need to be confident that the change is correct.
